[theme]
base = "dark"
primaryColor = "#000000"
secondaryBackgroundColor = "#5274b8"
textColor = "#f8c7ff"
backgroundColor = "#000000"
font = "serif"
headingFont = "sans-serif"

[theme.sidebar]
font = "sans-serif"
textColor = "#f4adad"
